src/Entity/HotelRooms.php
<?php

namespace App\Entity;

use App\Repository\HotelRoomsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HotelRoomsRepository::class)]
class HotelRooms
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 50)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'decimal', precision: 6, scale: 2)]
    private $price;

    #[ORM\Column(type: 'string', length: 255)]
    private $booking_link;

    #[ORM\ManyToMany(targetEntity: Images::class, inversedBy: 'hotelRooms')]
    private $Images;

    #[ORM\OneToMany(mappedBy: 'hotelRooms', targetEntity: ReservationRooms::class)]
    private $Reservation_rooms;

    #[ORM\ManyToOne(targetEntity: Hotels::class, inversedBy: 'Hotel_rooms')]
    #[ORM\JoinColumn(nullable: false)]
    private $hotels;

    public function __construct()
    {
        $this->Images = new ArrayCollection();
        $this->Reservation_rooms = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getBookingLink(): ?string
    {
        return $this->booking_link;
    }

    public function setBookingLink(string $booking_link): self
    {
        $this->booking_link = $booking_link;

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->Images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->Images->contains($image)) {
            $this->Images[] = $image;
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        $this->Images->removeElement($image);

        return $this;
    }

    /**
     * @return Collection<int, ReservationRooms>
     */
    public function getReservationRooms(): Collection
    {
        return $this->Reservation_rooms;
    }

    public function addReservationRoom(ReservationRooms $reservationRoom): self
    {
        if (!$this->Reservation_rooms->contains($reservationRoom)) {
            $this->Reservation_rooms[] = $reservationRoom;
            $reservationRoom->setHotelRooms($this);
        }

        return $this;
    }

    public function removeReservationRoom(ReservationRooms $reservationRoom): self
    {
        if ($this->Reservation_rooms->removeElement($reservationRoom)) {
            // set the owning side to null (unless already changed)
            if ($reservationRoom->getHotelRooms() === $this) {
                $reservationRoom->setHotelRooms(null);
            }
        }

        return $this;
    }

    public function getHotels(): ?Hotels
    {
        return $this->hotels;
    }

    public function setHotels(?Hotels $hotels): self
    {
        $this->hotels = $hotels;

        return $this;
    }

    public function __toString() {
        return $this->getTitle();
    }
}

src/Controller/SuitesController.php
<?php

namespace App\Controller;

use App\Entity\HotelRooms;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SuitesController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    #[Route('/suites/{id}', name: 'app_suites')]
    public function index($id): Response
    {

        $suites = $this->entityManager->getRepository(HotelRooms::class)->findBy(array('hotels' => $id));
        $hoteltitle = $this->entityManager->getRepository(HotelRooms::class)->findOneBy(array('hotels' => $id));
        return $this->render('suites/index.html.twig', [
            'suites' => $suites,
            'hoteltitle' => $hoteltitle
        ]);



    }
}

templates/suites/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Suites{% endblock %}

{% block body %}
<main>
    <div class="row  justify-content-center text-center">
        <h3 class="col-md-4 mt-5 mb-2">{{hoteltitle.hotels }}</h3>
    </div>
    <article class="row justify-content-center">{% for suite in suites %}
        <section class="seaview col-md-4 d-flex flex-column text-center p-4 align-items-center m-5">
            <h4 class="mt-2 mb-2">{{ suite.title }}</h4>

            <div id="suite{{suite.id}}" class="carousel slide mt-2 mb-4" data-bs-ride="carousel">
               <div class="carousel-inner">
                    {% for image in suite.images %}
                        <div class="carousel-item {% if loop.index==1 %}active{% endif %}">
                            <img src="{{ asset('img/'~ image.bin)}}" alt="{{ suite.title }}" class="d-block w-100 card-img">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#suite{{suite.id}}" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#suite{{suite.id}}" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <p>{{suite.description }}</p>
            <a href="{{path('app_reservations', {hotel:suite.hotels.id, suite:suite.id})}}" class="btn bg-dark text-white w-15">Consulter les disponibilités</a>
            <br>
            <a href="{{suite.bookinglink}}" class="btn bg-dark text-white w-15" target="_blank">Lien Booking.com</a>
        </section>{% endfor %}
    </article>
{% endblock %}